### ISSUE TITLE
Incompatibilities with some markdownlint rules

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/auto-changelog#60]
This package produces `CHANGELOG.md` files that are incompatible with [`markdownlint`](https://github.com/DavidAnson/markdownlint).

The written changelog conforms exactly to the example from the [Keep a Changelog website](https://keepachangelog.com/en/1.0.0/), but are its spacing conventions really relevant to the spec our our ability to parse a changelog?

I believe that the spacing is irrelevant to the Keep a Changelog spec, and we should make the output changelogs compatible with `markdownlint` at least in terms of spacing. There may even be an argument to integrate `markdownlint` into this tool, but that's a different question.

Related: #50. `markdownlint`-compatibility appears to be largely equivalent with Prettier-compatibility.

**Comment by Gudahtt** [comment]
Changing the spacing, or some other unimportant aspect of the changelog format, is something we could do. But then it wouldn't be strictly compatible with the spec, and thus with other KeepAChangelog-related tooling. We could make it flexible, but then it would be less useful, because it can't apply the format for us automatically if it's flexible enough to accept both.

**Comment by danroc** [comment]
Update: Keep a Changelog has changed its own [changelog file](https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/v1.1.1/CHANGELOG.md) to match `markdownlint` defaults.

See: https://github.com/olivierlacan/keep-a-changelog/pull/318
